export default {
  'Clockwork Perspectives': [
    {
      author: ' CAITLIN JAMES AND PATRICK ZAILCKAS',
      thumbnail: 'the-building-blocks-of-successful-investor-reporting/rocks.jpg',
      category: 'Clockwork Perspectives',
      title: 'The Building Blocks Of Successful Investor Reporting',
      publishedAt: '2021-01-21',
      link: 'the-building-blocks-of-successful-investor-reporting',
      description:
        'When sitting down to build your next investor update, consider beginning by identifying the thematic areas you plan to address with your audience. Distilling your update into smaller, topic-based segments will make for a more approachable letter with a narrative that sticks. Ideally the structure stays consistent over time. ',
    },
    {
      author: 'CAITLIN JAMES AND PATRICK ZAILCKAS',
      thumbnail: 'striking-the-balance-investor-communications-dos-and-donts/surf.jpg',
      category: 'Clockwork Perspectives',
      title: 'Striking The Balance: Investor Communications DOs And DON’Ts',
      publishedAt: '2021-01-04 00:00',
      link: 'striking-the-balance-investor-communications-dos-and-donts',
      description:
        'As a founder, it is important to think about your investor relations strategy holistically. Take a step back from the individual updates, and consider how you can maximize both your effectiveness as a communicator and the value-add to your business over time. Before setting out to write your next investor letter, pause to consider some key opportu',
    },
    {
      author: 'Kyle Rose',
      thumbnail: 'performance-metrics-how-are-your-investors-judging-you/umbrellas.jpg',
      category: 'Clockwork Perspectives',
      title: 'Performance Metrics: How Are Your Investors Judging You?',
      publishedAt: '2021-02-02',
      link: 'performance-metrics-how-are-your-investors-judging-you',
      description:
        'Established or nascent, public or private, a fundamental truism to businesses is that they require capital (in some form) to grow. Especially in the early stages of a company’s lifecycle, choosing...',
    },
    {
      author: 'CAITLIN JAMES AND PATRICK ZAILCKAS',
      thumbnail: 'an-honest-approach-to-investor-relations/women-interview.jpg',
      category: 'Clockwork Perspectives',
      title: 'An Honest Approach To Investor Relations',
      publishedAt: '2020-12-23',
      link: 'an-honest-approach-to-investor-relations',
      description:
        'Established or nascent, public or private, a fundamental truism to businesses is that they require capital (in some form) to grow. Especially in the early stages of a company’s lifecycle, choosing...',
    },
    {
      author: 'BRIAN POCOCK & KYLE ROSE',
      thumbnail: 'key-performance-indicators-what-are-they-and-why-do-they-matter/notebooks-papers.jpg',
      category: 'Clockwork Perspectives',
      title: 'Key Performance Indicators: What Are They And Why Do They Matter?',
      publishedAt: '2021-02-17',
      link: 'key-performance-indicators-what-are-they-and-why-do-they-matter',
      description:
        'Across nearly every vertical of the investment industry investors and funds focus on a few key performance and return-oriented metrics, such as IRR and MOIC, to gauge the success of their work. But while these metrics are useful to investors, they provide little meaning to portfolio company founders.',
    },
    {
      author: 'PATRICK ZAILCKAS',
      thumbnail: 'the-flippening-founders-vs-funds-as-lead-investors/switch.jpg',
      category: 'Clockwork Perspectives',
      title: 'The Flippening: Founders vs Funds as Lead Investors',
      publishedAt: '2021-04-19',
      link: 'the-flippening-founders-vs-funds-as-lead-investors',
      description:
        'Is the age of institutional venture capital dwindling away?  There might be a case to make as access to private capital expands across the fat tail of the private investment market among family offices and angels.',
    },
    {
      author: 'KYLE ROSE',
      thumbnail: 'simple-agreement-for-future-equity-SAFE-an-overview/safe-future.jpg',
      category: 'Clockwork Perspectives',
      title: 'Simple Agreement for Future Equity (SAFE): An Overview',
      publishedAt: '2021-04-28',
      link: 'simple-agreement-for-future-equity-SAFE-an-overview',
      description:
        'Simple Agreements for Future Equity (SAFEs) are one of the simplest and most common forms of fundraising employed by early-stage founders.',
    },
    {
      author: 'CORY SHEA',
      thumbnail: 'sales-metrics/engine.jpeg',
      category: 'Clockwork Perspectives',
      title: 'Greasing the Sales Engine with Metrics',
      publishedAt: '2021-05-03',
      link: 'sales-metrics',
      description:
        'Broadly speaking, when it comes to tracking sales or business development related metrics it makes sense to break it down into two summary groups, 1) activities and 2) results.',
    },
    {
      author: 'KYLE ROSE',
      thumbnail: 'convertible-notes-an-overview/solar-panels.jpeg',
      category: 'Clockwork Perspectives',
      title: 'Convertible Notes: An Overview',
      publishedAt: '2021-05-04',
      link: 'convertible-notes-an-overview',
      description:
        'Convertible notes are the investor-friendly version of SAFEs, with the addition of features designed to enhance investor interests like maturity dates and interest rates.',
    },
    {
      author: 'CAITLIN JAMES',
      thumbnail: 'should-you-join-an-accelerator-3-big-questions-to-ask/people-working.jpeg',
      category: 'Clockwork Perspectives',
      title: 'Should you join an accelerator? 3 Big Questions to Ask',
      publishedAt: '2021-05-07',
      link: 'should-you-join-an-accelerator-3-big-questions-to-ask',
      description:
        'The decision to join an accelerator can be a difficult one, especially for first-time founders who are new to the startup world.',
    },
    {
      author: 'PATRICK ZAILCKAS',
      thumbnail: 'decentralized-finance-new-paradigms-on-how-we-business/looking-into-the-future.jpeg',
      category: 'Clockwork Perspectives',
      title: 'Decentralized Finance: New Paradigms on How We Business',
      publishedAt: '2021-05-10',
      link: 'decentralized-finance-new-paradigms-on-how-we-business',
      description:
        'You might feel like if you’re just hearing about the surge of crypto industry that you are late to the party. Perhaps you’re right on time, we may just be getting started. ',
    },
    {
      author: 'KYLE ROSE',
      thumbnail: 'common-equity-an-overview/viewing-chart-notebook.jpeg',
      category: 'Clockwork Perspectives',
      title: 'Common Equity: An Overview',
      publishedAt: '2021-05-12',
      link: 'common-equity-an-overview',
      description:
        'Unlike many of the more complicated transaction types often associated with private investments, common equity is about as straightforward as it gets. The very same type of instrument as the public stocks you trade (probably far too frequently) in your brokerage account, at its most fundamental level common equity simply represents ownership of a company.',
    },
    {
      author: 'PATRICK ZAILCKAS',
      thumbnail: 'introducing-the-diligence-series-applying-a-simple-framework/modern-achitecture.jpeg',
      category: 'Clockwork Perspectives',
      title: 'Introducing the Diligence Series: Applying a Simple Framework',
      publishedAt: '2021-05-18',
      link: 'introducing-the-diligence-series-applying-a-simple-framework',
      description:
        'When analyzing a new private investment opportunity, you may ask yourself “where do I begin?” While gut feeling, personal interests, pre-existing relationships, and capital availability are all important factors, it is best practice to honor a standard, objective approach to your assessment framework which adds clarity to the benefits, risks, and red flags of any opportunity crossing your plate. This article marks the beginning of a multi-post series on due diligence.',
    },
    {
      author: 'PAOLA SCHAAR',
      thumbnail: 'what-a-recession-would-mean-to-startups/money-jar.png',
      category: 'Clockwork Perspectives',
      title: 'What a recession would mean to startups',
      publishedAt: '2021-05-20',
      link: 'what-a-recession-would-mean-to-startups',
      description:
        'Unfortunately, we are currently experiencing a global economic recession. COVID-19 has taken a huge toll on businesses and economics around the world and most countries are struggling with rising unemployment, business bankruptcy and a significant reduction in aggregate demand.',
    },
    {
      author: 'PATRICK ZAILCKAS',
      thumbnail: 'diligence_series_weighing_the_value_proposition/puzzle.jpeg',
      category: 'Clockwork Perspectives',
      title: 'Diligence Series: Weighing the Value Proposition',
      publishedAt: '2021-05-24',
      link: 'diligence_series_weighing_the_value_proposition',
      description:
        'The first due diligence questions you will likely ask about any business are “what is it?”, “what does it do?”, “why does it exist?”, and, maybe, “who cares?” And it’s not difficult to see why.',
    },
  ],
  'Clockwork Investor Series': [
    {
      thumbnail: 'investor-series/sep-alavi.jpg',
      category: 'Clockwork Investor Series',
      title: 'Interview With Sep Alavi',
      publishedAt: '2021-01-10',
      link: 'interview-with-sep-alavi',
      description: 'Interview with sep alavi',
      fundName: 'White Star Capital Digital Asset',
    },
    {
      thumbnail: 'investor-series/alejandro-diez-barroso.jpg',
      category: 'Clockwork Investor Series',
      title: 'Interview With Alejandro Diez Barroso',
      publishedAt: '2021-01-27',
      link: 'interview-with-alejandro-diez-barroso',
      description: 'Interview with alejandro diez barroso',
      fundName: 'DILA Capital',
    },
    {
      thumbnail: 'investor-series/odile-roujol.jpeg',
      category: 'Clockwork Investor Series',
      title: 'Interview With Odile Roujol',
      publishedAt: '2021-02-23',
      link: 'interview-with-odile-roujol',
      description: 'Interview with Odile Roujol',
      fundName: 'Fab Ventures, Fund I',
    },
    {
      thumbnail: 'investor-series/vaughn-blake.jpeg',
      category: 'Clockwork Investor Series',
      title: 'Interview With Vaughn Blake',
      publishedAt: '2021-03-10',
      link: 'interview-with-vaughn-blake',
      description: 'Interview With Vaughn Blake',
      fundName: 'Blue Bear Capital',
    },
    {
      thumbnail: 'investor-series/kevin-leonard.jpeg',
      category: 'Clockwork Investor Series',
      title: 'Interview With Kevin Leonard',
      publishedAt: '2021-03-24',
      link: 'interview-with-kevin-leonard',
      description: 'Interview With Kevin Leonard',
      fundName: 'MissionOG',
    },
    {
      thumbnail: 'investor-series/nisa-amoils.jpeg',
      category: 'Clockwork Investor Series',
      title: 'Interview With Nisa Amoils',
      publishedAt: '2021-04-14',
      link: 'interview-with-nisa-amoils',
      description: 'Interview With Nisa Amoils (A100x Ventures)',
      fundName: 'A100x Ventures',
    },
    {
      thumbnail: 'investor-series/paul-nolde.jpg',
      category: 'Clockwork Investor Series',
      title: 'Interview With Paul Nolde',
      publishedAt: '2021-04-28',
      link: 'interview-with-paul-nolde',
      description: 'Interview with Paul Nolde (Riverflow Growth Fund)',
      fundName: 'Riverflow Growth Fund',
    },
    {
      thumbnail: 'investor-series/jai-malik.jpeg',
      category: 'Clockwork Investor Series',
      title: 'Interview With Jai Malik',
      publishedAt: '2021-05-12',
      link: 'interview-with-jai-malik',
      description: 'Interview With Jai Malik (Countdown Capital)',
      fundName: 'Countdown Capital',
    },
  ],
}
