export default {
  'Clockwork Perspectives': [
    {
      author: ' CAITLIN JAMES AND PATRICK ZAILCKAS',
      thumbnail: 'rocks.jpg',
      category: 'Clockwork Perspectives',
      title: 'The Building Blocks Of Successful Investor Reporting',
      publishedAt: '2021-01-21',
      link: 'the-building-blocks-of-successful-investor-reporting',
      description:
        'When sitting down to build your next investor update, consider beginning by identifying the thematic areas you plan to address with your audience. Distilling your update into smaller, topic-based segments will make for a more approachable letter with a narrative that sticks. Ideally the structure stays consistent over time. ',
    },
    {
      author: 'CAITLIN JAMES AND PATRICK ZAILCKAS',
      thumbnail: 'surf.jpg',
      category: 'Clockwork Perspectives',
      title: 'Striking The Balance: Investor Communications DOs And DON’Ts',
      publishedAt: '2021-01-04 00:00',
      link: 'striking-the-balance-investor-communications-dos-and-donts',
      description:
        'As a founder, it is important to think about your investor relations strategy holistically. Take a step back from the individual updates, and consider how you can maximize both your effectiveness as a communicator and the value-add to your business over time. Before setting out to write your next investor letter, pause to consider some key opportu',
    },
    {
      author: 'Kyle Rose',
      thumbnail: 'umbrellas.jpg',
      category: 'Clockwork Perspectives',
      title: 'Performance Metrics: How Are Your Investors Judging You?',
      publishedAt: '2021-02-02',
      link: 'performance-metrics-how-are-your-investors-judging-you',
      description:
        'Established or nascent, public or private, a fundamental truism to businesses is that they require capital (in some form) to grow. Especially in the early stages of a company’s lifecycle, choosing...',
    },
    {
      author: 'CAITLIN JAMES AND PATRICK ZAILCKAS',
      thumbnail: 'women.jpg',
      category: 'Clockwork Perspectives',
      title: 'An Honest Approach To Investor Relations',
      publishedAt: '2020-12-23',
      link: 'an-honest-approach-to-investor-relations',
      description:
        'Established or nascent, public or private, a fundamental truism to businesses is that they require capital (in some form) to grow. Especially in the early stages of a company’s lifecycle, choosing...',
    },
    {
      author: 'BRIAN POCOCK & KYLE ROSE',
      thumbnail: 'notebooks-papers.jpg',
      category: 'Clockwork Perspectives',
      title: 'Key Performance Indicators: What Are They And Why Do They Matter?',
      publishedAt: '2021-02-17',
      link: 'key-performance-indicators-what-are-they-and-why-do-they-matter',
      description:
        'Across nearly every vertical of the investment industry investors and funds focus on a few key performance and return-oriented metrics, such as IRR and MOIC, to gauge the success of their work. But while these metrics are useful to investors, they provide little meaning to portfolio company founders.',
    },
    {
      author: 'PATRICK ZAILCKAS',
      thumbnail: 'switch.jpg',
      category: 'Clockwork Perspectives',
      title: 'The Flippening: Founders vs Funds as Lead Investors',
      publishedAt: '2021-04-19',
      link: 'the-flippening-founders-vs-funds-as-lead-investors',
      description:
        'Is the age of institutional venture capital dwindling away?  There might be a case to make as access to private capital expands across the fat tail of the private investment market among family offices and angels.',
    },
    {
      author: 'KYLE ROSE',
      thumbnail: 'safe-future.jpg',
      category: 'Clockwork Perspectives',
      title: 'Simple Agreement for Future Equity (SAFE): An Overview',
      publishedAt: '2021-04-28',
      link: 'simple-agreement-for-future-equity-SAFE-an-overview',
      description:
        'Simple Agreements for Future Equity (SAFEs) are one of the simplest and most common forms of fundraising employed by early-stage founders.',
    },
    {
      author: 'CORY SHEA',
      thumbnail: 'rktkn-BZ9z9ZeUjbI-unsplash.jpeg',
      category: 'Clockwork Perspectives',
      title: 'Greasing the Sales Engine with Metrics',
      publishedAt: '2021-05-03',
      link: 'sales-metrics',
      description:
        'Broadly speaking, when it comes to tracking sales or business development related metrics it makes sense to break it down into two summary groups, 1) activities and 2) results.',
    },
  ],
  'Clockwork Investor Series': [
    {
      thumbnail: 'sep-alavi.jpg',
      category: 'Clockwork Investor Series',
      title: 'Interview With Sep Alavi',
      publishedAt: '2021-01-10',
      link: 'interview-with-sep-alavi',
      description: 'Interview with sep alavi',
      fundName: 'White Star Capital Digital Asset',
    },
    {
      thumbnail: 'alejandro.jpg',
      category: 'Clockwork Investor Series',
      title: 'Interview With Alejandro Diez Barroso',
      publishedAt: '2021-01-27',
      link: 'interview-with-alejandro-diez-barroso',
      description: 'Interview with alejandro diez barroso',
      fundName: 'DILA Capital',
    },
    {
      thumbnail: 'odile.jpeg',
      category: 'Clockwork Investor Series',
      title: 'Interview With Odile Roujol',
      publishedAt: '2021-02-23',
      link: 'interview-with-odile-roujol',
      description: 'Interview with Odile Roujol',
      fundName: 'Fab Ventures, Fund I',
    },
    {
      thumbnail: 'vaughn-blake.jpeg',
      category: 'Clockwork Investor Series',
      title: 'Interview With Vaughn Blake',
      publishedAt: '2021-03-10',
      link: 'interview-with-vaughn-blake',
      description: 'Interview With Vaughn Blake',
      fundName: 'Blue Bear Capital',
    },
    {
      thumbnail: 'kevin-leonard.jpeg',
      category: 'Clockwork Investor Series',
      title: 'Interview With Kevin Leonard',
      publishedAt: '2021-03-24',
      link: 'interview-with-kevin-leonard',
      description: 'Interview With Kevin Leonard',
      fundName: 'MissionOG',
    },
    {
      thumbnail: 'nisa-amoils.jpeg',
      category: 'Clockwork Investor Series',
      title: 'Interview With Nisa Amoils',
      publishedAt: '2021-04-14',
      link: 'interview-with-nisa-amoils',
      description: 'Interview With Nisa Amoils (A100x Ventures)',
      fundName: 'A100x Ventures',
    },
    {
      thumbnail: 'Paul-Nolde.jpg',
      category: 'Clockwork Investor Series',
      title: 'Interview With Paul Nolde',
      publishedAt: '2021-04-28',
      link: 'interview-with-paul-nolde',
      description: 'Interview with Paul Nolde',
      fundName: 'Riverflow Growth Fund',
    },
  ],
}
